services:
  #nginx
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html

  #php
  app:
   build:
     dockerfile: docker/php/Dockerfile
   volumes:
      - /var/www/html/vendor
      - ./app:/var/www/html
   environment:
     MYSQL_HOST: db
     MYSQL_PORT: ${MYSQL_PORT}
     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
     MYSQL_DATABASE: ${MYSQL_DATABASE}
     MYSQL_USER: ${MYSQL_USER}


  #mysql
  db:
     image: mysql:latest
     volumes:
       - db-data:/var/lib/mysql
     ports:
       - "3306:3306"
     restart: unless-stopped
     environment:
         MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
         MYSQL_USER: ${MYSQL_USER}
         MYSQL_PASSWORD: ${MYSQL_PASSWORD}
         MYSQL_DATABASE: ${MYSQL_DATABASE}

  #phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    ports:
      - 8080:80
volumes:
  db-data:
